### PR TITLE
Add typings

### LINKED ISSUE #10: Consider adding TypeScript support
Hey,
First of all, thank you for the project.

Have you considered adding typings to add support for TypeScript? Here's link to issue to help doing that.
typings/typings#322

### PR DESCRIPTION
**Pull request by bilby91**
Fixes #10

### CODE REVIEW

**Comment by bilby91** [comment]
Let me know if you want to remove the lock file.

**Comment by MauriceButler** [comment]
:+1: Thanks for this.

I am happy for the lock file to be there.

This looks like a good start, but from my limited TS knowledge does this also need to allow for the optional arguments to the constructor? 

I think it would need to be something like this

```
constructor(options: BunyanLoggly.IOptions, bufferLength? : number, bufferTimeout?: number, logglyCallback?: Function);
```

But I honestly dont know what I am doing in TS so happy for you to correct me.

**Comment by bilby91** [comment]
You are right! Will fix that soon. Thanks!

**Comment by bilby91** [comment]
@MauriceButler Done!

**Pull request merged**
