### PR TITLE
fixed dangling comma which causes issues on node 6

### PR DESCRIPTION
**Pull request by rizowski**
Fixes: #33

### CODE REVIEW

**Comment by dncrews** [comment]
This took down our production authentication today. Please get this published ASAP before everything else goes down too. We're trying quickly to upgrade dozens of node versions across our apps in the mean time. Please get there first.

**Comment by stephan-nordnes-eriksen** [comment]
@dncrews This caused issues for us too, but we locked our version to 1.3.5, and that works fine.

And I think we both learned the lesson to properly lock version in production environment :)

**Comment by dncrews** [comment]
@MauriceButler any chance of this even happening?

**Comment by MauriceButler** [comment]
Thanks everyone, I honestly wasnt even still thinking about node 6 support.
Ill merge this in and republish.

**Comment by MauriceButler** [comment]
[bunyan-loggly@1.4.1](https://github.com/MauriceButler/bunyan-loggly/releases/tag/v1.4.1) has been published to resolve this.

**Pull request merged**
